# config配置连接地址
# 外网
DATABASE_OUTSIDE_HOST = '106.14.206.19'
DATABASE_OUTSIDE_PORT = 3306
DATABASE_OUTSIDE_USER = 'root'    # 用户名
DATABASE_OUTSIDE_PASSWORD = '123456'   # 密码
DATABASE_OUTSIDE_DB = 'kepler'   # 数据库名称
DATABASE_OUTSIDE_CHARSET = 'utf8'


# 内网
DATABASE_INTRANET_HOST = '106.14.206.19'
DATABASE_INTRANET_PORT = 3306
DATABASE_INTRANET_USER = 'root'    # 用户名
DATABASE_INTRANET_PASSWORD = '123456'   # 密码
DATABASE_INTRANET_DB = 'kepler'   # 数据库名称
DATABASE_INTRANET_CHARSET = 'utf8'